/**
 * Port the harrison-saito-morel template's stylesheets and copy into this site.
 *
 * Dion, 18 Sep 2026: below the hero, the home page is the Morel build
 * (harrison-saito-morel.vercel.app). Its CSS is a whole design system written
 * for its own document — bare `h1`, `body`, `:root`, and class names this site
 * already uses (`.section`, `.btn`, `.eyebrow`, `.hero`, `.footer`, `.lede`).
 * Loaded as-is it would restyle every page here. So every selector is put
 * under `.mo`, the wrapper MorelHome.astro renders, `:root`/`html`/`body`
 * become `.mo` itself, and the rules for chrome this site keeps its own of
 * (header, promo bar, mobile menu, footer, consent bar, the Morel heroes,
 * the /book page) are dropped.
 *
 * The copy comes across the same way: the template's src/data/site.ts is
 * copied whole to src/data/morel-source.ts (no parsing), and src/data/morel.ts
 * re-exports what the home page uses with the template's routes mapped onto
 * this site's pages.
 *
 * Re-run after the template changes:
 *   node scripts/morel/sync.mjs
 *
 * Source: ../WEB - Harrison Saito Morel Template/src/{styles,data}.
 * Output: src/styles/morel.css and src/data/morel-source.ts (both generated —
 * edit morel-overrides.css / morel.ts instead).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const TEMPLATE = path.resolve(ROOT, '..', 'WEB - Harrison Saito Morel Template');
const SRC = path.join(TEMPLATE, 'src', 'styles');
const FILES = ['global.css', 'sections.css', 'motion.css', 'landing.css'];
const OUT = path.join(ROOT, 'src', 'styles', 'morel.css');
const SCOPE = '.mo';

/* Chrome this site keeps its own of. A rule goes only if every one of its
   selectors starts with one of these. `.hero__ctas` / `.hero__more` are
   Morel-hero-only too. */
const DROP = /^(\.header|\.promo|\.nav\b|\.nav__|\.mmenu|\.footer|\.consent|\.hero\b|\.hero__|\.hero--|\.book\b|\.book-|\.book__|\.inner-hero--book|\.intent|\.channel|\.cal\b|\.cal__|\.story\b|\.story__)/;

/* Assets the template references that live under a new, versioned name here
   (/img carries a one-year immutable cache). */
const URLS = [['/img/enso-watermark.png', '/img/mo/enso-watermark-v1.webp']];

function scope(sel) {
  const s = sel.trim();
  if (s === ':root' || s === 'html' || s === 'body') return SCOPE;
  if (/^(html|body|:root)[.:[]/.test(s)) return s.replace(/^(html|body|:root)/, SCOPE);
  if (s.startsWith('.no-js ')) return `.no-js ${SCOPE} ${s.slice(7)}`;
  return `${SCOPE} ${s}`;
}

let css = '';
for (const f of FILES) css += `\n/* ===== ${f} ===== */\n` + fs.readFileSync(path.join(SRC, f), 'utf8');

const root = postcss.parse(css);
let dropped = 0;

root.walkAtRules('font-face', (at) => {
  /* Avant is declared once for the site in avant.css. The 'Accent' faces point
     at the Cormorant files this site already self-hosts, so they stay. */
  if (/Avant/.test(at.toString())) at.remove();
});

root.walkRules((rule) => {
  const parent = rule.parent;
  if (parent && parent.type === 'atrule' && /keyframes$/i.test(parent.name)) return;
  if (rule.selectors.every((s) => DROP.test(s.trim()))) {
    rule.remove();
    dropped++;
    return;
  }
  rule.selectors = rule.selectors.filter((s) => !DROP.test(s.trim())).map(scope);
});

/* Media blocks emptied by the drop. */
root.walkAtRules('media', (at) => { if (!at.nodes || at.nodes.length === 0) at.remove(); });

let out = root.toString();
for (const [from, to] of URLS) out = out.split(from).join(to);

const header = `/* GENERATED by scripts/morel/sync.mjs from the harrison-saito-morel
   template — do not edit by hand. Overrides live in morel-overrides.css. */\n@import './avant.css';\n`;
fs.writeFileSync(OUT, header + out.replace(/\n{3,}/g, '\n\n'));
console.log(`wrote ${path.relative(ROOT, OUT)} — ${(out.length / 1024).toFixed(1)} KB, ${dropped} chrome rules dropped`);

const DATA_SRC = path.join(TEMPLATE, 'src', 'data', 'site.ts');
const DATA_OUT = path.join(ROOT, 'src', 'data', 'morel-source.ts');
fs.writeFileSync(
  DATA_OUT,
  `/* GENERATED by scripts/morel/sync.mjs — a verbatim copy of the harrison-saito-morel\n   template's src/data/site.ts. Do not edit; src/data/morel.ts maps it onto this site. */\n` +
    fs.readFileSync(DATA_SRC, 'utf8')
);
console.log(`wrote ${path.relative(ROOT, DATA_OUT)}`);
