/**
 * Self-host the two brand faces.
 *
 * The legacy site pulled Cormorant Garamond + Nunito Sans from fonts.googleapis.com,
 * which costs a render-blocking third-party connection on every visit and leaks
 * visitor IPs to Google. Self-hosting removes both and lets us preload the two
 * faces that actually paint the LCP element.
 *
 * Run once: node scripts/fetch-fonts.mjs
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'public', 'fonts');

// Requesting with a modern browser UA gets us woff2; latin subset only.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FAMILIES = [
  {
    slug: 'cormorant-garamond',
    css: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400&display=swap',
  },
  {
    slug: 'nunito-sans',
    css: 'https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;500;600;700&display=swap',
  },
];

await fs.mkdir(OUT, { recursive: true });

const faces = [];

for (const fam of FAMILIES) {
  const css = await (await fetch(fam.css, { headers: { 'User-Agent': UA } })).text();

  // Each @font-face block carries its unicode-range; we only keep `latin`,
  // which is the last block Google emits per weight/style.
  const blocks = css.split('@font-face').slice(1);
  let i = 0;
  for (const block of blocks) {
    if (!/unicode-range:[^;]*U\+0000-00FF/.test(block)) continue; // latin only

    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
    const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal';
    if (!url) continue;

    const name = `${fam.slug}-${weight}${style === 'italic' ? '-italic' : ''}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await fs.writeFile(path.join(OUT, name), buf);

    const family = fam.slug === 'nunito-sans' ? 'Nunito Sans' : 'Cormorant Garamond';
    faces.push({ family, name, weight, style, size: buf.length });
    i++;
  }
  console.log(`${fam.slug}: ${i} latin faces`);
}

// Emit the @font-face CSS the site imports.
const css = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */
${faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.name}') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,
    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
    U+2212, U+2215, U+FEFF, U+FFFD;
}`
  )
  .join('\n\n')}
`;

await fs.writeFile(path.join(ROOT, 'src', 'styles', 'fonts.css'), css, 'utf8');

const total = faces.reduce((a, f) => a + f.size, 0);
console.log(`\n${faces.length} files, ${(total / 1024).toFixed(0)} KB total`);
console.log('wrote src/styles/fonts.css');
