/* GENERATED by scripts/morel/sync.mjs — a verbatim copy of the harrison-saito-morel
   template's src/data/site.ts. Do not edit; src/data/morel.ts maps it onto this site. */
/**
 * Single source of truth for every string on the site.
 *
 * Structure follows dannymorel.com section for section (docs/DIAGNOSIS.md has
 * the map). The CONTENT is Harrison's, lifted from harrisonsaito.com.au —
 * his story, his five patterns, his three phases, his quote, his films, his
 * FAQ answers and his legal pages. Anything marked PLACEHOLDER is template
 * filler awaiting sign-off.
 *
 * Offer structure (Dion, 12 Sep 2026): 1:1 coaching · monthly breathwork
 * workshops · Return to Self = "The Core". Nothing youth-related.
 *
 * Paid-traffic cut (17 Sep 2026): this page is the destination for the Meta
 * ad set. No VSL and no testimonials — neither exists yet — so the page has
 * to hold on its own: story, patterns, lineage, straight answers, and one
 * low-friction next step (a discovery chat) instead of an application form.
 */

export const SITE = {
  name: 'Harrison Saito',
  legalName: 'Harrison Saito',
  domain: 'https://harrison-saito-morel.vercel.app',
  tagline: 'Martial Artist · Coach',
  locality: 'Chatswood, NSW',
  email: 'hello@harrisonsaito.com.au',
  phone: '+61424657548',
  phoneDisplay: '+61 424 657 548',
  whatsappBase: 'https://wa.me/61424657548',
  whatsapp: 'https://wa.me/61424657548?text=' + encodeURIComponent("Hi Harrison, I'd like to book a discovery chat."),
  instagram: 'https://www.instagram.com/harrison.saito/',
  youtube: 'https://www.youtube.com/@Harrison_saito',
  facebook: 'https://www.facebook.com/shinbukanmartialarts/',
  linkedin: 'https://www.linkedin.com/in/harrison-saito',
  description:
    'Men’s coaching with Harrison Saito: 1:1 coaching, monthly breathwork workshops and The Core, the 12-week Return to Self programme. Karate, Buddhism and structured inner work in Chatswood, NSW.',
} as const;

/* Verified external links (see docs/DIAGNOSIS.md §7). */
export const LINKS = {
  sbsWorldNews: 'https://www.youtube.com/watch?v=YnHlcZLzu50',
  sbsArticle:
    'https://www.sbs.com.au/news/small-business-secrets/article/karate-helps-mental-physcial-health/sglf9zcfw',
  sbsJapanese:
    'https://www.sbs.com.au/language/japanese/en/podcast-episode/generational-and-cultural-divides-within-a-family-two-cultures-coming-together-at-a-karate-dojo/vlc7i0h27',
  inTheCove: 'https://inthecove.com.au/2025/04/12/how-a-japanese-karate-grandmaster-came-to-teach-in-lane-cove/',
  shinbukan: 'https://www.shinbukan.com.au/the-saitos',
  seizanji: 'https://www.shingon.org.au/about',
  liveSite: 'https://www.harrisonsaito.com.au',
} as const;

export const VIDEO = {
  sbsWorldNews: 'YnHlcZLzu50',
  fatherSonShort: 'm-r7VUuoBfc',
  chakra: 'XJ5Xjqmdvo8',
} as const;

/* --------------------------------------------------------------- tracking */

/**
 * The live site (harrisonsaito.com.au) already runs Google Tag Manager
 * container GTM-5GPC5FDS, which carries its GA4 and Meta Pixel with consent
 * mode. The same container here means the ad set's landing page reports into
 * the same properties. Set `gtmId: ''` to ship without any tracking.
 *
 * Consent defaults to denied (analytics + ads) until the visitor accepts,
 * matching what the Privacy Policy below promises. CTA clicks push
 * `cta_click` / `contact_click` events onto the dataLayer for GTM to map to
 * Lead / Contact conversions.
 */
export const TRACKING = {
  gtmId: 'GTM-5GPC5FDS',
};

export const CONSENT = {
  text: 'We use cookies to measure how this site is used and to improve our advertising. You can decline without losing any functionality.',
  linkLabel: 'See our Privacy Policy',
  linkHref: '/privacy',
  accept: 'Accept',
  decline: 'Decline',
};

/* ------------------------------------------------------------- promo bar */

/* Morel's promo pushes the live event; ours names the offer the ads sell. */
export const PROMO = {
  badge: 'Return',
  badgeSub: 'to self',
  text: 'Twelve weeks, one to one, for a small number of men at a time. Chatswood and online.',
  /* On a phone the bar sits above the hero, so it gets the short line. */
  textShort: 'Twelve weeks, one to one. Chatswood and online.',
  cta: 'Book a discovery chat',
  href: '/book',
};

/* -------------------------------------------------------------------- nav */

export type NavItem = { label: string; href?: string; children?: { label: string; href: string; external?: boolean }[] };

export const NAV: NavItem[] = [
  {
    label: 'Coaching',
    href: '/return-to-self',
    children: [
      { label: 'The Core — Return to Self', href: '/return-to-self' },
      { label: '1:1 Coaching', href: '/coaching' },
      { label: 'Book a Discovery Chat', href: '/book' },
    ],
  },
  { label: 'Workshops', href: '/workshops' },
  {
    label: 'Resources',
    href: '/resources',
    children: [
      { label: 'Films & Media', href: '/resources' },
      { label: 'SBS World News feature', href: LINKS.sbsWorldNews, external: true },
      { label: '5-Minute Guided Meditation', href: `https://www.youtube.com/watch?v=${VIDEO.chakra}`, external: true },
    ],
  },
  { label: 'Straight Answers', href: '/#faq' },
  { label: 'The Story', href: '/story' },
];

export const NAV_CTA = { label: 'Book a chat', href: '/book' };

/* ------------------------------------------------------------------- hero */

/**
 * Hero copy is ours, not Morel's. "From the inside out" was his verbatim and
 * is gone. The two halves read as one sentence: break what you inherited,
 * build what is yours — Dion's brief (self-worth, compassion, habits you
 * never chose) in Harrison's own vocabulary of inherited pattern vs chosen self.
 *
 * The primary button goes straight to the conversation — paid traffic gets
 * one next step. The quiet link under it is for the man who needs to read
 * first.
 */
export const HERO = {
  titleLines: ['Break The', 'Habits You', '<mark>Never Chose.</mark>'],
  accent: 'Separate. Return. <em>Integrate.</em>',
  cta: { label: 'Book a discovery chat', href: '/book' },
  secondary: { label: 'Not ready? Start here', href: '#for-you' },
  /* His own line, from the live site's lineage headline. */
  quoteLines: ['It is not therapy.', 'It is a dojo.'],
  bigLines: ['Rebuild', 'Self-Worth'],
  mobileTitle: 'Break The Habits You Never Chose. <mark>Rebuild Self-Worth.</mark>',
  /* Hero A (route /hero-a): karate-gi portrait in the dojo, cut out with scripts/cutout.py. */
  photo: '/img/harrison-hero-gi.webp',
  photoAlt: 'Harrison Saito seated in a karate gi and black belt',
  /* Hero B (the home page): Harrison holding a lit match in the dojo, full bleed —
     the same frame his own landing page leads with. */
  photoB: '/img/hero-match.webp',
  photoBAlt: 'Harrison Saito holding a lit match up to his face in the dojo, shoji screens glowing behind him',
};

/**
 * Hero C (the home page from 17 Sep): one frame of the Return to Self film,
 * held, pushing forward on scroll. Copy is Dion's 17 Sep hero line.
 */
export const HERO_FRAME = {
  eyebrow: 'Harrison Saito · Men’s coaching · Chatswood, Sydney',
  title: 'Son of a <mark>Karate Grand Master</mark>',
  sub: '17+ Years Karate | Coach | Buddhist',
  still: 'rts-still-v1',
  widths: [768, 1280, 1920, 2560],
  alt: 'A traditional Japanese room, its sliding doors open onto an alcove with a hanging scroll',
  aria: 'Harrison Saito — Return to Self',
};

/* ------------------------------------------------------- who this is for */

/**
 * The scan-in-ten-seconds block. Every line is a compression of something
 * Harrison already wrote (the `source` sentences behind his five patterns,
 * and the Core lede). Icons are our own minimal gold line marks — no stock
 * icon set, nothing borrowed.
 */
export type ForYouCard = { icon: string; text: string; emphasis: string };

export const FOR_YOU_SECTION = {
  label: 'Who This Is For',
  title: 'You built the life that looks right. <mark>It does not feel like yours.</mark>',
  lede: 'If more than one of these lands, you are in the right place. They tend to travel together.',
  cta: { label: 'Book a discovery chat', href: '/book' },
};

export const FOR_YOU: ForYouCard[] = [
  { icon: 'mask', text: 'They call you solid,', emphasis: 'you feel like a fraud.' },
  { icon: 'saidmeant', text: 'You say yes when you mean no,', emphasis: 'then call it keeping the peace.' },
  { icon: 'loop', text: 'You chase an approval', emphasis: 'you never actually feel.' },
  { icon: 'ember', text: 'There is an anger underneath', emphasis: 'you cannot name.' },
  { icon: 'bar', text: 'You still meet a standard', emphasis: 'someone else set.' },
  { icon: 'distance', text: 'You want to be close,', emphasis: 'and keep everyone at arm’s length.' },
];

/* ------------------------------------------------------ as-seen-on strip */

export type Logo = {
  label: string;
  href: string;
  img?: string;
  width: number;
  suffix?: string;
  style?: 'serif' | 'sans' | 'condensed' | 'wide';
};

export const LOGOS: Logo[] = [
  { label: 'SBS World News', href: LINKS.sbsWorldNews, img: '/img/logo-sbs-world-news.svg', width: 140 },
  { label: 'SBS Japanese', href: LINKS.sbsJapanese, img: '/img/logo-sbs.svg', width: 64, suffix: 'Japanese' },
  { label: 'In the Cove', href: LINKS.inTheCove, width: 120, style: 'serif' },
  { label: 'Shinbukan', href: LINKS.shinbukan, img: '/img/mark-shinbukan-dark.png', width: 44 },
  { label: 'Seizanji', href: LINKS.seizanji, img: '/img/mark-seizanji-dark.png', width: 80 },
];

/* ------------------------------------------------------------------ intro */

export const INTRO = {
  small: 'Martial arts. Buddhism. Honest inner work.',
  /* Harrison's own words, live site "The Story". `em` = italic run. */
  big: 'The same tools that caused my trauma became the exact things that set me free. That is not a turn of phrase. It is the <em>method</em>, and it is why I do not teach anything I have not been through.',
  cta: { label: 'The Story', href: '/story' },
};

/* ------------------------------------------------------------------ story */

/* Verbatim from harrisonsaito.com.au — the section that opens his home page after the film. */
export const STORY_SECTION = {
  label: 'The Story',
  /* Dion, 14 Sep: lead with the father's own struggle — it is what readers
     recognise themselves in, and it is what Harrison's direction grew out of.
     NEEDS HARRISON'S SIGN-OFF: it is a public claim about a living relative. */
  titleHtml: 'My father was addicted to <mark>fighting and anger.</mark>',
  subtitle: 'A war survivor, a karate grandmaster, and later a practising Buddhist monk.',
  videoId: VIDEO.sbsWorldNews,
  videoTitle: 'SBS World News — Harrison Saito',
  /* Click to play. No iframe loads until the visitor asks for it — faster on
     a phone off an ad, and it keeps the Privacy Policy's promise that video
     embeds load only on play. */
  poster: '/img/sbs-group.webp',
  posterAlt: 'Harrison Saito with students at the Shinbukan dojo, from the SBS World News feature',
  playLabel: 'Watch the SBS feature',
  paragraphs: [
    'He gave me discipline. He gave me martial arts. He gave me Buddhism. He also gave me <strong>people-pleasing, suppressed rage, and a five-year-old frozen inside a grown man’s body.</strong>',
    'I took all of it, the gift and the wound, and walked a path that only I could walk.',
  ],
  cta: { label: 'Read the full story', href: '/story' },
  /* Verified credentials — replaces Morel's four unverifiable vanity numbers. */
  numbers: [
    { value: '10+', label: 'Years coaching men in Chatswood, NSW.' },
    { value: '2nd Dan', label: 'Black belt. Training since the age of 11.' },
    { value: '3', label: 'Generations of Japanese karate lineage.' },
    { value: 'SBS', label: 'National broadcast feature on SBS World News.' },
  ],
};

/* --------------------------------------------------------- the patterns */

/**
 * The five patterns, verbatim from the live site's archetype coverflow.
 * Every one is a named pattern drawn from a sentence of Harrison's own copy
 * (`source`), so nothing here is invented framework.
 */
export type Pattern = {
  number: string;
  name: string;
  kanji: string;
  romaji: string;
  kanjiMeaning: string;
  recognise: string;
  cost: string;
  through: string;
};

export const PATTERNS_SECTION = {
  label: 'The Patterns',
  title: 'Which one is <mark>running you?</mark>',
  lede: 'Most men who come to me are not carrying a problem. They are carrying a pattern — one they inherited, never chose, and have never once been able to name.',
  why: 'Naming it is not a personality quiz. It is the first move of the actual work: <em>self-trust begins when you can tell the difference between an inherited reaction and what you genuinely think, feel and value.</em> You cannot separate a pattern you cannot see.',
  foot: 'Recognised yourself in more than one? That is the usual answer — they tend to travel together.',
  /* The training now sits above the patterns, so this points on to its page. */
  cta: { label: 'See how the training undoes them', href: '/return-to-self' },
};

export const PATTERNS: Pattern[] = [
  {
    number: '01',
    name: 'The Performer',
    kanji: '仮面',
    romaji: 'kamen',
    kanjiMeaning: 'the mask',
    recognise:
      'You are competent in every room and known in none of them. The version of you that other people rely on has been running so long you are no longer certain what is underneath it.',
    cost: 'Exhaustion that sleep does not touch, and a private sense of being a fraud in a life you actually built.',
    through:
      'Separating the performance from the person — not demolishing it. The competence is real. It just stops being the only thing you are allowed to be.',
  },
  {
    number: '02',
    name: 'The Dutiful Son',
    kanji: '孝',
    romaji: 'kō',
    kanjiMeaning: 'filial duty',
    recognise:
      'You are still, at some level, answering to a standard someone else set. You may have exceeded it. It did not help. The bar moved, or the person who set it never acknowledged that you cleared it.',
    cost: 'A life optimised for an approval that was never going to arrive, and a relationship you cannot name as grief because he is still alive.',
    through:
      'Going back to the origin. Understanding where the pattern came from — the father, the family system, the culture — and processing what is actually there.',
  },
  {
    number: '03',
    name: 'The Peacekeeper',
    kanji: '和',
    romaji: 'wa',
    kanjiMeaning: 'harmony, at any price',
    recognise:
      'You read a room before you enter it. You know what everyone needs and you supply it. Asked what you want, you go blank — not because you do not know, but because wanting has never been the safe move.',
    cost: 'Resentment you cannot justify, relationships built on a version of you that never disagrees, and a slow disappearance.',
    through: 'Boundaries without guilt. Saying the true thing and staying in the room while it lands.',
  },
  {
    number: '04',
    name: 'The Achiever',
    kanji: '功',
    romaji: 'kō',
    kanjiMeaning: 'merit, earned',
    recognise:
      'Achievement is the only currency you fully trust. Each one lands for about a day. Then the floor resets and you are behind again, measured against a standard that exists nowhere but in you.',
    cost: 'A career that looks like success and feels like a treadmill, and a body that has been running on discipline instead of rest for years.',
    through:
      'Discovering that the discipline was never the problem — the reason for it was. The strength stays. What it serves changes.',
  },
  {
    number: '05',
    name: 'The Held Fist',
    kanji: '怒',
    romaji: 'ikari',
    kanjiMeaning: 'anger, held',
    recognise:
      'It leaks — in traffic, at your kids, at nothing. Or it never leaks at all, which is worse, because it has to be held down every single day and holding it is most of what you do.',
    cost: 'Something in you the people closest to you have learned to move around, and a five-year-old still frozen inside a grown man.',
    through: 'Meeting it in the body rather than analysing it. This is where the martial arts stop being metaphor.',
  },
];

/* ------------------------------------------------------------ the core */

/**
 * 守破離 shu-ha-ri — hold the form, break the form, leave the form — mapped
 * onto his three phases. Phase copy is verbatim from the live site.
 */
export const PHASES = [
  {
    number: '01',
    kanji: '守',
    romaji: 'shu',
    weeks: 'Key one · Weeks 1–4',
    name: 'Separate',
    body: 'See the pattern for what it is — the people-pleasing, the performing, the held-down anger — and pull it apart from what you actually think, feel and value. You cannot break free of what you cannot see.',
  },
  {
    number: '02',
    kanji: '破',
    romaji: 'ha',
    weeks: 'Key two · Weeks 5–8',
    name: 'Return',
    body: 'Go back to where it started — your father, your family, your culture — and train the response, not the story. This is where the real work happens: in the body, not in theory.',
  },
  {
    number: '03',
    kanji: '離',
    romaji: 'ri',
    weeks: 'Key three · Weeks 9–12',
    name: 'Integrate',
    body: 'Build the daily practice that holds it. Boundaries without guilt. The discipline stays, the strength stays — and now they answer to you.',
  },
];

export const CORE = {
  label: 'The Training',
  title: 'Return to Self.',
  lede: 'A twelve-week training for anyone who wants to break free of the patterns they never chose. Three keys, handed over in order — Separate, Return, Integrate — and trained one to one until you hold them yourself.',
  /* His own line from the live programme page, in the training's register. */
  note: 'This is not therapy. It is training: a framework for the inner world, built on martial arts, Buddhism and honest self-inquiry. In person around Chatswood and Sydney’s North Shore, or online Australia-wide.',
  ctas: [
    { label: 'Start the training', href: '/book', style: 'filled' },
    { label: 'What the twelve weeks contain', href: '/return-to-self', style: 'outline' },
  ],
};

/* -------------------------------------------------------- straight answers */

/**
 * The objections a man has on the way down the page, answered before he has
 * to ask. The first five are verbatim from the "Before You Apply — Straight
 * answers" block on harrisonsaito.com.au. The rest are new, written to the
 * same rules: plain Australian register, training not treatment, no promises
 * of outcome, and the crisis line wherever crisis is mentioned.
 */
export type Faq = { q: string; a: string };

/**
 * Dion, 17 Sep: this block is the no-pressure block. There is more than one
 * way in — some men need the foundations (the story, the upbringing, the
 * lineage) before the application makes sense; some want the twelve weeks
 * laid out; some just want to talk. Offer the avenues, answer the questions,
 * and let him book when he is ready.
 */
export const FAQ_SECTION = {
  label: 'No Pressure',
  title: 'There is more than <mark>one way in.</mark>',
  lede: 'Some men want the foundations first — where this comes from, the father, the lineage, the upbringing — before they can trust how it is applied. Some want the twelve weeks laid out plainly. Some just want to talk. Start wherever you are, and book when you are ready. Not before.',
  avenues: [
    { label: 'The foundations', sub: 'The story, and the lineage it grew out of', href: '/story' },
    { label: 'The application', sub: 'How the twelve weeks actually run', href: '/return-to-self' },
    { label: 'When you are ready', sub: 'A conversation, not a pitch', href: '/book' },
  ],
  answersLabel: 'Straight answers, in the meantime',
  cta: { label: 'Book when you’re ready', href: '/book' },
};

export const FAQ: Faq[] = [
  {
    q: 'Is this therapy?',
    a: 'No. This is coaching — a training framework for the inner world, built on martial arts, Buddhism and honest self-inquiry. It is not therapy, diagnosis or emergency care, and it is not a replacement for any of them. If you are in crisis, contact Lifeline on 13 11 14.',
  },
  {
    q: 'Do I need martial arts experience?',
    a: 'No. Karate is used as a method for working with the nervous system, attention and pressure. Plenty of men arrive having never trained. The physical practice is adapted to the person in front of me.',
  },
  {
    q: 'How much does it cost?',
    a: 'We cover that on the first conversation, once I understand what you are actually carrying and whether I can help. I will not put you through a pitch to get to it — ask directly and I will answer directly.',
  },
  {
    q: 'Where do sessions happen?',
    a: 'In person around Chatswood and Sydney’s North Shore, or online Australia-wide.',
  },
  {
    q: 'How much do I have to disclose?',
    a: 'You are never required to disclose more than you choose, or to prove yourself through an exercise. The pacing is adapted to you.',
  },
  {
    q: 'What actually happens on the discovery chat?',
    a: 'A short call, by phone or video. You talk first. I ask a few direct questions about where you are and what you have already tried. Then you get a straight answer on whether the twelve weeks fit you — and if they do not, where to look instead.',
  },
  {
    q: 'Is Buddhism part of it? Do I need to be religious?',
    a: 'No. Buddhism here is attention training — two and a half thousand years of practical method for watching your own mind. There is no belief to adopt, no ritual to perform and nothing you will be asked to sign up to.',
  },
  {
    q: 'I am not in crisis. Is this still for me?',
    a: 'It is built for exactly that. Most men who come are functioning well by every outside measure — the job, the family, the discipline — and cannot say why it feels hollow. You do not need to be falling apart to start. If you are in crisis, this is not the right door: contact Lifeline on 13 11 14 or your GP first.',
  },
  {
    q: 'How is this different from a men’s group or a retreat?',
    a: 'It is one to one, it runs for twelve weeks with a fixed end date, and it happens inside your ordinary life — not over one intense weekend you then have to come down from. The work is in the body as much as in conversation, and it is paced to you.',
  },
  {
    q: 'What do I tell my partner?',
    a: 'The truth, plainly: that you are doing twelve weeks of structured training with a coach on the patterns you inherited, and that it is not therapy and not a replacement for it. You are welcome to bring them into the first conversation.',
  },
  {
    q: 'Is this a cult, or something woo?',
    a: 'No. It is one man, a dojo, and twelve weeks with a fixed end date. The lineage is real and checkable — Shinbukan, Chatswood, since 1978 — and so is the temple. There is nothing you have to join and nowhere you have to fly to.',
  },
  {
    q: 'Who is it not for?',
    a: 'Men who want someone else to do the work, men who book the call to be talked into or out of it, and anyone in acute crisis — who needs clinical care first. In that case I will say so and help you find it.',
  },
];

/* ------------------------------------------------------------ workshops */

export const WORKSHOPS = {
  label: 'Ways In',
  title: 'Come as you are. <mark>Return to yourself.</mark>',
  cta: { label: 'See all workshops', href: '/workshops' },
  cards: [
    {
      tag: 'Monthly · In-Person',
      title: 'Breathwork Workshop',
      /* PLACEHOLDER details: dates, price and format still to be confirmed with Harrison. */
      body: 'A monthly small-group somatic breathwork session in Chatswood, capped at sixteen. Regulation first; everything else follows.',
      cta: { label: 'Learn more', href: '/workshops' },
      image: '/img/coaching-dharma.webp',
      lockup: ['Breath', 'Work'],
    },
    {
      tag: 'Session by session',
      title: '1:1 Coaching',
      body: 'Karate and Buddhist philosophy for inner work, nervous system regulation, and breaking the people-pleasing pattern. Session-based, at your pace.',
      cta: { label: 'Learn more', href: '/coaching' },
      image: '/img/karate-training.webp',
      lockup: ['One', 'To One'],
    },
  ],
};

/* ------------------------------------------------------------- the quote */

/* The line his live site gives a full dark band to. */
export const QUOTE = {
  text: 'Compassion naturally arises when the illusion of separation softens.',
  image: '/img/ink-wash.webp',
};

/* ----------------------------------------------------------------- films */

export const FILMS_SECTION = {
  label: 'As Seen On',
  title: 'See the <mark>work.</mark>',
  cta: { label: 'All films & interviews', href: '/resources' },
};

/**
 * Cards use Harrison's own photography, not the YouTube thumbnails — his
 * shorts are vertical, so their thumbnails arrive pillarboxed with burnt-in
 * captions and break the grade.
 */
export const FILMS = [
  {
    id: VIDEO.sbsWorldNews,
    label: 'As Seen On',
    title: 'SBS World News',
    description: 'The national broadcast feature on youth and adult mental health.',
    image: '/img/sbs-group.webp',
    featured: true,
  },
  {
    id: VIDEO.fatherSonShort,
    label: 'Featured',
    title: 'A father & son talk & heal',
    image: '/img/father-son-still.webp',
  },
  {
    id: VIDEO.chakra,
    label: 'Guided Practice',
    title: '5 Minute Guided Chakra Meditation',
    image: '/img/buddha.webp',
  },
];

/* ----------------------------------------------------------------- doors */

export const FAMILY = {
  label: 'Work with Harrison',
  title: 'Choose the door that <mark>fits where you are.</mark>',
  body: 'One to one, a monthly breathwork room, or the twelve-week core. Martial arts, Buddhism and honest inner work, at your pace.',
  big: {
    title: 'The Core',
    body: 'Return to Self. 12 weeks. Three phases: Separate, Return, Integrate. A structured programme for men who are done performing.',
    cta: { label: 'Learn more', href: '/return-to-self' },
    image: '/img/about-bed.webp',
    lockup: ['The', 'Core'],
  },
  cards: [
    {
      title: '1:1 Coaching',
      lockup: ['One', 'To One'],
      body: 'Karate and Buddhist philosophy for inner work, nervous system regulation, and breaking the people-pleasing pattern.',
      cta: { label: 'Learn more', href: '/coaching' },
      image: '/img/karate-training.webp',
    },
    {
      tag: 'Monthly',
      title: 'Breathwork Workshop',
      lockup: ['Breath', 'Work'],
      accent: 'Somatic breathwork, small group, sixteen places',
      body: 'Once a month in Chatswood. Regulate the nervous system in a room of sixteen, then take the practice home.',
      cta: { label: 'Learn more', href: '/workshops' },
      image: '/img/buddha.webp',
    },
  ],
};

/* --------------------------------------------------------------- closing */

export const CLOSE = {
  title: 'If something here resonated, <mark>reach out.</mark>',
  body: 'No pitch. No pressure. Just a conversation about where you are and what you’re looking for.',
  ctas: [
    { label: 'Book a discovery chat', href: '/book', style: 'filled' },
    { label: 'Email instead', href: `mailto:${SITE.email}`, style: 'outline' },
  ],
};

/* ------------------------------------------------------------- newsletter */

export const NEWSLETTER = {
  titleLines: ['Daily practice.', 'Daily regulation.', 'Daily momentum.'],
  body: 'Get the 5-minute guided practice that pulls you out of autopilot.',
  /* PLACEHOLDER endpoint — swap for the GHL / lead endpoint when it exists. */
  action: '',
  placeholder: 'Your email address',
  cta: 'Send it to me',
  fallbackHref: `https://www.youtube.com/watch?v=${VIDEO.chakra}`,
};

/* ----------------------------------------------------------------- footer */

export const FOOTER = {
  copyright: `© ${new Date().getFullYear()} Harrison Saito.`,
  rights: 'All rights reserved.',
  /* His live site's footer line, word for word. */
  disclaimer: 'Coaching and mentoring. Not therapy, diagnosis or emergency care.',
  legal: [
    { label: 'Privacy Policy', href: '/privacy' },
    { label: 'Terms & Conditions', href: '/terms' },
  ],
  columns: [
    {
      heading: 'About',
      links: [
        { label: 'The Story', href: '/story' },
        { label: 'Resources', href: '/resources' },
        { label: 'Straight Answers', href: '/#faq' },
        { label: 'Contact Us', href: `mailto:${SITE.email}` },
      ],
    },
    {
      heading: 'Programs',
      links: [
        { label: 'The Core — Return to Self', href: '/return-to-self' },
        { label: '1:1 Coaching', href: '/coaching' },
        { label: 'Monthly Breathwork Workshop', href: '/workshops' },
        { label: 'Book a Discovery Chat', href: '/book' },
      ],
    },
    {
      heading: 'Lineage',
      links: [
        { label: 'Shinbukan Martial Arts', href: LINKS.shinbukan, external: true },
        { label: 'Seizanji Temple', href: LINKS.seizanji, external: true },
        { label: 'SBS World News', href: LINKS.sbsWorldNews, external: true },
      ],
    },
  ],
  marquee: ['Separate', 'Return', 'Integrate'],
};

/* ------------------------------------------------------------------ book */

/**
 * The conversion page for the ad set. One low-friction step: pick the line
 * that fits, tap WhatsApp (or call, or email) and the message is already
 * written. No form, no backend, nothing to wait for. When a booking or CRM
 * endpoint exists, it slots in beside these without replacing them.
 *
 * The intents are the five conversion triggers from the acquisition
 * strategy, in the man's words, plus the live site's own "I'd rather say it
 * on the call".
 */
export const BOOK = {
  slug: 'book',
  label: 'Get started',
  title: 'Book a discovery chat',
  lede: 'This starts with a conversation, not a pitch. Tell me where you are, and I will tell you honestly whether I can help.',
  intentLabel: 'Where are you right now?',
  intentHint: 'Pick the closest one. It goes into the message so we can skip the small talk.',
  intents: [
    { id: 'performing', label: 'Performing on empty' },
    { id: 'anger', label: 'An anger I can’t explain' },
    { id: 'relationship', label: 'A relationship on thin ice' },
    { id: 'father', label: 'I just became a father' },
    { id: 'drifting', label: 'Drifting. Something is off.' },
    { id: 'call', label: 'I’d rather say it on the call' },
  ],
  messageOpen: 'Hi Harrison, I’d like to book a discovery chat.',
  messagePrefix: 'Where I am right now:',
  channels: {
    whatsapp: { label: 'Message on WhatsApp', sub: 'Fastest. One tap, reply usually the same day.' },
    call: { label: 'Call', sub: SITE.phoneDisplay },
    email: { label: 'Email', sub: SITE.email, subject: 'Discovery chat' },
  },
  replyNote: 'I read every message myself. Expect a reply within two business days — usually a call, if you leave a number.',
  callTitle: 'What happens on the call',
  callSteps: [
    'You talk first. Where you are, in your own words.',
    'A few direct questions about what you have already tried and what has not moved.',
    'A straight answer on whether the twelve weeks fit you — and if not, where to look instead.',
  ],
  /* The standards paragraph, adapted from the acquisition strategy. Naming
     the third group first is what makes the rule land as an invitation. */
  beforeTitle: 'A word before we speak',
  before:
    'Some men book this call to be talked out of it. Some book it to argue. That is fine — but it is not what this call is for, and I do not hold time for it. The men I work with show up on time, say the true thing even when it is awkward, and treat their word as the first rep of the training. I take a small number of men at a time. If that is you, I will see you on the call.',
  /* Verbatim from the live site's application page. */
  crisis: 'This is coaching, not therapy, diagnosis or emergency care. If you are in crisis, please contact Lifeline on 13 11 14.',
  crisisHref: 'https://www.lifeline.org.au/',
};

/**
 * Calendly, inline on /book beneath the intent pills (Dion, 17 Sep 2026).
 * WhatsApp, call and email stay beside it. Leave `url` empty and the block
 * does not render at all. The chosen intent is passed as the answer to the
 * event's first custom question (`a1`), so add one question to the Calendly
 * event ("Where are you right now?") and it arrives pre-filled.
 */
export const CALENDLY = {
  url: '', // e.g. 'https://calendly.com/harrisonsaito/discovery-chat'
  label: 'Or pick a time now',
  sub: 'Twenty minutes, phone or video. Choose a slot and it is in both diaries.',
  loadLabel: 'Show available times',
  height: 720,
};

/* ------------------------------------------------ inner pages (level one) */

export type InnerSection = { heading?: string; paragraphs: string[]; list?: string[] };
export type InnerPage = {
  slug: string;
  label: string;
  title: string;
  lede: string;
  image?: string;
  sections: InnerSection[];
  cta?: { label: string; href: string };
};

export const PAGES: InnerPage[] = [
  {
    slug: 'return-to-self',
    label: 'The Core — 12 weeks',
    title: 'Return to Self',
    lede: 'Twelve weeks. Three phases — Separate, Return, Integrate. One-to-one training for men who built the life that looks right and cannot say why it feels hollow.',
    image: '/img/dark-dojo.webp',
    sections: [
      {
        heading: 'Who it is for',
        paragraphs: [
          'People describe you as “solid.” “Reliable.” “Disciplined.” They have no idea that underneath all of that, you’re exhausted from performing a version of yourself that isn’t even you.',
          'Often connected to a father who demanded everything and gave you no room to be human. And underneath the performance, there’s a simmering anger you can’t quite name.',
        ],
      },
      {
        heading: 'What it is, and is not',
        paragraphs: [
          'This is not therapy. It is coaching: a training framework for the inner world, built on martial arts, Buddhism, and honest self-inquiry. Over 12 weeks, you learn to recognise inherited reactions earlier, separate them from your own values, and make choices you can stand behind.',
          'The exact pacing and exercises are adapted to the person in front of me. You are never required to disclose more than you choose or prove yourself through an exercise. This is coaching, not therapy, diagnosis or emergency care.',
          'In person around Chatswood and Sydney’s North Shore, or online Australia-wide.',
        ],
      },
    ],
    cta: { label: 'Book a Discovery Chat', href: '/book' },
  },
  {
    slug: 'coaching',
    label: 'One to one',
    title: '1:1 Coaching',
    lede: 'Using Karate and Buddhist philosophy for inner work, nervous system regulation, and breaking the people-pleasing pattern. Session-based, at your pace.',
    image: '/img/coaching-dharma.webp',
    sections: [
      {
        heading: 'How it works',
        paragraphs: [
          'One-to-one sessions in Chatswood or online. No programme to commit to; the work goes at the pace your life allows.',
          'It is not therapy. It is a dojo.',
        ],
      },
    ],
    cta: { label: 'Book a Discovery Chat', href: '/book' },
  },
  {
    slug: 'workshops',
    label: 'Monthly · In-person',
    title: 'Breathwork Workshop',
    lede: 'A monthly small-group somatic breathwork session in Chatswood, capped at sixteen. Regulation first; everything else follows.',
    image: '/img/buddha.webp',
    sections: [
      {
        heading: 'Why breath first',
        paragraphs: [
          /* Harrison, unprompted, on the 26 Aug 2026 tape. */
          '“The biggest tool that helps me is regulation. I’ve got to regulate my state.” — Harrison',
          'The workshop is the door. The Core is the road. Come once, and you will know whether the road is yours.',
        ],
      },
      {
        heading: 'Next dates',
        /* PLACEHOLDER — dates, price and what to bring to be confirmed. */
        paragraphs: ['Next dates to be announced. Reserve a place and you will be the first to hear.'],
      },
    ],
    cta: { label: 'Reserve a place', href: '/book' },
  },
  {
    slug: 'story',
    label: 'The Story',
    title: 'Between two countries.',
    lede: 'Japanese father. Australian upbringing. For most of my life I was fluent in both and at home in neither.',
    image: '/img/hero-poster.webp',
    sections: [
      {
        heading: 'A war survivor, a martial artist, a monk.',
        paragraphs: [
          'My father survived post-WW2 Japan. He was a martial artist and a Buddhist monk.',
          'He gave me discipline. He gave me martial arts. He gave me Buddhism. He also gave me people-pleasing, suppressed rage, and a five-year-old frozen inside a grown man’s body.',
        ],
      },
      {
        heading: 'The gift and the wound were the same object.',
        paragraphs: [
          'I took all of it, the gift and the wound, and walked a path that only I could walk.',
          'The same tools that caused my trauma became the exact things that set me free. That is not a turn of phrase. It is the method, and it is why I do not teach anything I have not been through.',
        ],
      },
      {
        heading: 'Where the work happens now.',
        paragraphs: [
          'Today I help men stop performing and start living through martial arts, Buddhism, and structured inner work.',
        ],
      },
    ],
    cta: { label: 'Work with Harrison', href: '/book' },
  },
  {
    slug: 'resources',
    label: 'Films & Media',
    title: 'Resources',
    lede: 'Films, features and guided practices from Harrison’s channel.',
    image: '/img/father-son-still.webp',
    sections: [
      {
        heading: 'Watch',
        paragraphs: [
          `SBS World News — the national broadcast feature: https://www.youtube.com/watch?v=${VIDEO.sbsWorldNews}`,
          `A father & son talk & heal: https://www.youtube.com/watch?v=${VIDEO.fatherSonShort}`,
          `5 Minute Guided Chakra Meditation: https://www.youtube.com/watch?v=${VIDEO.chakra}`,
        ],
      },
    ],
  },
  {
    slug: BOOK.slug,
    label: BOOK.label,
    title: BOOK.title,
    lede: BOOK.lede,
    sections: [],
  },

  /* ------------------------------------------------------------- legal
     Verbatim from harrisonsaito.com.au/privacy and /terms (last updated
     5 August 2026) — the same sole trader, the same services, the same
     processors, so his existing policy covers this page too. The only edit
     is the site-specific note about video embeds, which now matches how this
     page behaves. Both pages carry his own "not legal advice" footnote. */
  {
    slug: 'privacy',
    label: 'Legal · Last updated 5 August 2026',
    title: 'Privacy Policy',
    lede: 'This policy explains how Harrison Saito (“I”, “me”, “my”) collects, uses, stores and discloses your personal information. It is written to comply with the Australian Privacy Act 1988 (Cth) and the Australian Privacy Principles (APPs).',
    sections: [
      {
        heading: 'Who is responsible',
        paragraphs: [
          'Harrison Saito, a sole trader providing coaching, mentoring and tutoring services from Chatswood, New South Wales, Australia, is the entity responsible for the personal information collected through this website.',
        ],
      },
      {
        heading: 'What I collect',
        paragraphs: ['Information you give me. When you complete a form on this site, or message me from it, I collect:'],
        list: [
          'your name;',
          'your email address;',
          'your phone number, where you provide it;',
          'your general location, where you provide it;',
          'the content of your message, including anything you choose to tell me about your circumstances, what you have tried previously, and what you are looking for.',
        ],
      },
      {
        paragraphs: [
          'Some of what you may choose to share — for example, information touching on your mental or emotional wellbeing — could be sensitive information under the Privacy Act. You are never required to disclose more than you choose. Where you do share it, I collect it only with your consent and only to decide whether and how I can help you.',
          'Information collected automatically. If you consent to analytics and advertising cookies, I collect standard web analytics data: pages viewed, approximate location derived from IP address, device and browser type, referral source, scroll depth, and which buttons or links you interact with. If you decline, this collection does not take place.',
        ],
      },
      {
        heading: 'Why I collect it',
        paragraphs: [],
        list: [
          'To respond to your enquiry and arrange a conversation.',
          'To assess whether a programme or service is a suitable fit for you.',
          'To deliver services you engage me for, and to communicate with you about them.',
          'To understand how this website is used and improve it.',
          'To measure the effectiveness of advertising, where you have consented.',
        ],
      },
      {
        paragraphs: [
          'I do not sell your personal information. I do not use your information for automated decision-making that produces a legal or similarly significant effect on you.',
        ],
      },
      {
        heading: 'Cookies and tracking',
        paragraphs: [
          'This site uses cookies and similar technologies. Strictly necessary cookies are always active. Analytics and advertising cookies are set to denied by default and are only enabled if you accept them via the consent notice. You can change your decision at any time by clearing this site’s data in your browser.',
          'Where you consent, the following may be used:',
        ],
        list: [
          'Google Analytics 4 and Google Tag Manager (Google LLC) — website analytics and tag delivery.',
          'Meta Pixel and Conversions API (Meta Platforms, Inc.) — advertising measurement. Where a conversion is sent to Meta from my server, identifiers such as your email address and phone number are irreversibly hashed with SHA-256 before transmission; Meta does not receive them in readable form.',
        ],
      },
      {
        paragraphs: [
          'Video embeds are not loaded until you click play, and they use YouTube’s youtube-nocookie.com domain. If you never press play, YouTube sets no cookies.',
        ],
      },
      {
        heading: 'Who I share it with',
        paragraphs: ['I share personal information only with service providers that help me operate this business, and only to the extent necessary:'],
        list: [
          'website and form hosting infrastructure;',
          'email delivery services, so I can reply to you;',
          'messaging services, where you choose to contact me through them;',
          'scheduling software, where you book a time;',
          'analytics and advertising platforms, where you have consented.',
        ],
      },
      {
        paragraphs: [
          'Some of these providers store or process data outside Australia, including in the United States and the European Union. By using this site and contacting me through it, you acknowledge that your information may be disclosed to overseas recipients. I take reasonable steps to ensure such recipients handle your information consistently with the APPs.',
        ],
      },
      {
        heading: 'How long I keep it',
        paragraphs: [
          'Enquiries that do not lead to an engagement are retained for up to 24 months, then deleted. Records relating to clients are retained for seven years, in line with Australian record keeping obligations. Analytics data is retained according to the platform’s own retention settings.',
        ],
      },
      {
        heading: 'Security',
        paragraphs: [
          'Information is transmitted over encrypted connections (HTTPS) and stored with reputable providers that maintain industry-standard security controls. No system is perfectly secure, and I cannot guarantee absolute security, but I take reasonable steps to protect your information from misuse, interference, loss and unauthorised access, modification or disclosure.',
        ],
      },
      {
        heading: 'Your rights',
        paragraphs: ['Under the Australian Privacy Principles you may:'],
        list: [
          'request access to the personal information I hold about you;',
          'request that I correct information that is inaccurate, out of date or incomplete;',
          'request that I delete your information, subject to my legal retention obligations;',
          'withdraw your consent to analytics and advertising cookies at any time;',
          'ask to deal with me anonymously or by pseudonym, where it is lawful and practicable.',
        ],
      },
      {
        paragraphs: ['To make a request, email hello@harrisonsaito.com.au. I will respond within 30 days.'],
      },
      {
        heading: 'Complaints',
        paragraphs: [
          'If you believe your privacy has been breached, contact me first at hello@harrisonsaito.com.au and I will investigate and respond within 30 days. If you are not satisfied with my response, you may complain to the Office of the Australian Information Commissioner at oaic.gov.au or on 1300 363 992.',
        ],
      },
      {
        heading: 'Children',
        paragraphs: [
          'Where I work with students under 18, I collect information from a parent or guardian, and consent for that engagement is given by the parent or guardian. This website is not directed at children, and I do not knowingly collect personal information from a person under 16 through this site.',
        ],
      },
      {
        heading: 'Changes',
        paragraphs: [
          'I may update this policy from time to time. The version in force is the one published on this page, with its date shown above.',
        ],
      },
      {
        heading: 'Contact',
        paragraphs: [
          'Harrison Saito, Chatswood, NSW, Australia. hello@harrisonsaito.com.au · +61 424 657 548',
          'This policy has been prepared to reflect how this website actually operates. It is not legal advice. Have it reviewed by an Australian legal practitioner before relying on it, and update it whenever a new data processor is introduced.',
        ],
      },
    ],
  },
  {
    slug: 'terms',
    label: 'Legal · Last updated 5 August 2026',
    title: 'Terms of Service',
    lede: 'These terms govern your use of this website and any coaching, mentoring or tutoring services provided by Harrison Saito. By using this site or engaging my services, you agree to them.',
    sections: [
      {
        heading: '1. Nature of the services — please read this one',
        paragraphs: [
          'I provide coaching, mentoring and tutoring. I am not a psychologist, psychiatrist, counsellor, social worker or medical practitioner, and nothing I provide is psychological treatment, medical advice, diagnosis, or emergency care.',
          'Coaching is a training framework for the inner world. It draws on martial arts, Buddhist philosophy and structured self-inquiry. It is not a substitute for treatment of a mental health condition. If you have or suspect you have a mental health condition, please consult a registered health practitioner. I may decline or end an engagement where I believe clinical support would serve you better, and I will say so directly.',
          'If you are in crisis or at risk of harm, contact Lifeline on 13 11 14, the Suicide Call Back Service on 1300 659 467, or call 000 immediately. Do not use this website to reach me for urgent matters — messages are not monitored continuously.',
        ],
      },
      {
        heading: '2. No guarantee of outcome',
        paragraphs: [
          'Coaching and tutoring outcomes depend substantially on your own effort, honesty and circumstances. I do not guarantee any particular result, including any ATAR, mark, rank, income, relationship or emotional outcome. Any client experience described on this site is an individual experience and is not a promise of similar results.',
        ],
      },
      {
        heading: '3. Engagement, fees and payment',
        paragraphs: [
          'Fees published on this site are in Australian dollars and include GST where applicable.',
          'Session-based coaching and mentoring are payable per session unless otherwise agreed in writing.',
          'The Return to Self programme is a 12-week engagement. Payment terms, including any instalment arrangement, are agreed in writing before the programme begins.',
          'Submitting an enquiry or booking a discovery chat does not create a binding engagement. An engagement begins when I confirm it and you accept the agreed terms.',
          'I may change published fees at any time; changes do not affect an engagement already agreed.',
        ],
      },
      {
        heading: '4. Cancellation and rescheduling',
        paragraphs: [
          'Individual sessions may be rescheduled with at least 24 hours’ notice at no charge. Sessions cancelled with less notice, or missed, may be charged in full.',
          'For the 12-week programme, you may withdraw at any time. Fees for sessions already delivered are non-refundable. Any refund of the unused balance is at my discretion and will be dealt with reasonably and in good faith.',
          'If I need to cancel or reschedule, I will offer an alternative time or refund the affected portion.',
        ],
      },
      {
        heading: '5. Confidentiality',
        paragraphs: [
          'What you tell me in a session stays between us. I will not disclose it without your consent, except where disclosure is required by law, or where I hold a reasonable belief that disclosure is necessary to prevent a serious and imminent threat to the life, health or safety of any person.',
        ],
      },
      {
        heading: '6. Students under 18',
        paragraphs: [
          'Where a student is under 18, a parent or guardian must arrange the engagement and is responsible for fees. I may share general progress with the parent or guardian. I hold a current Working With Children Check, which can be provided on request.',
        ],
      },
      {
        heading: '7. Your responsibilities',
        paragraphs: [],
        list: [
          'Provide accurate information about your circumstances and any relevant health matters.',
          'Attend sessions on time and engage in good faith.',
          'Take responsibility for your own decisions and actions arising from our work.',
          'Seek appropriate professional support where a matter falls outside coaching.',
        ],
      },
      {
        heading: '8. Intellectual property',
        paragraphs: [
          'All content on this website — text, images, video, programme structure and materials — is owned by Harrison Saito or used with permission, and is protected by copyright. Materials provided to you during an engagement are for your personal use and may not be reproduced, distributed or resold without written permission.',
        ],
      },
      {
        heading: '9. Liability',
        paragraphs: [
          'Nothing in these terms excludes, restricts or modifies any guarantee, right or remedy you have under the Australian Consumer Law that cannot lawfully be excluded. Where liability can be limited, my liability is limited to resupplying the services or paying the cost of having them resupplied.',
          'To the extent permitted by law, I am not liable for indirect or consequential loss arising from your use of this website or the services.',
        ],
      },
      {
        heading: '10. Website use',
        paragraphs: [
          'This website is provided on an “as is” basis. I may change or withdraw content at any time. Links to third-party sites are provided for convenience and do not imply endorsement or responsibility for their content.',
        ],
      },
      {
        heading: '11. Privacy',
        paragraphs: ['Personal information is handled in accordance with the Privacy Policy, which forms part of these terms.'],
      },
      {
        heading: '12. Governing law',
        paragraphs: [
          'These terms are governed by the laws of New South Wales, Australia. The courts of New South Wales have non-exclusive jurisdiction over any dispute.',
        ],
      },
      {
        heading: '13. Contact',
        paragraphs: [
          'Harrison Saito, Chatswood, NSW, Australia. hello@harrisonsaito.com.au · +61 424 657 548',
          'These terms have been drafted to reflect how this business actually operates. They are not legal advice. Have them reviewed by an Australian legal practitioner before relying on them — particularly clauses 3, 4 and 9, which carry commercial risk.',
        ],
      },
    ],
  },
];
